http:
  host: localhost
  port: "8080"

controller:
  work_queue_event_retries: 5

kubernetes:
  api_server:
    host: localhost
    port: "9000"

postgres:
  host: localhost
  port: "5432"
  user: reactor
  password: reactor
  database: reactor-controller
