apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  # name must match the spec fields below, and be in the form: <plural>.<group>
  name: reactors.huyage.dev
spec:
  # group name to use for REST API: /apis/<group>/<version>
  group: huyage.dev
  # list of versions supported by this CustomResourceDefinition
  versions:
    - name: v1alpha1
      # Each version can be enabled/disabled by Served flag.
      served: true
      # One and only one version must be marked as the storage version.
      storage: true
      schema:
        openAPIV3Schema:
          type: object
          properties:
            spec:
              type: object
              properties:
                reagent:
                  type: object
                  properties:
                    name:
                      type: string
                  required:
                    - name
                deployment:
                  type: object
                  properties:
                    replicas:
                      type: integer
                      default: 1
                    template:
                      type: object
                      properties:
                        metadata:
                          type: object
                          properties:
                            annotations:
                              type: object
                              additionalProperties:
                                type: string
                            labels:
                              type: object
                              additionalProperties:
                                type: string
                            name:
                              type: string
                            namespace:
                              type: string
                        spec:
                          type: object
                          properties:
                            containers:
                              type: array
                              items:
                                type: object
                                properties:
                                  args:
                                    type: array
                                    items:
                                      type: string
                                  command:
                                    type: array
                                    items:
                                      type: string
                                  env:
                                    type: array
                                    items:
                                      type: object
                                      properties:
                                        name:
                                          type: string
                                        value:
                                          type: string
                                        valueFrom:
                                          type: object
                                          properties:
                                            configMapKeyRef:
                                              type: object
                                              properties:
                                                key:
                                                  type: string
                                                name:
                                                  type: string
                                                optional:
                                                  type: boolean
                                              required:
                                                - key
                                            fieldRef:
                                              type: object
                                              properties:
                                                apiVersion:
                                                  type: string
                                                fieldPath:
                                                  type: string
                                              required:
                                                - fieldPath
                                            resourceFieldRef:
                                              type: object
                                              properties:
                                                containerName:
                                                  type: string
                                                divisor:
                                                  type: string
                                                resource:
                                                  type: string
                                              required:
                                                - resource
                                            secretKeyRef:
                                              type: object
                                              properties:
                                                key:
                                                  type: string
                                                name:
                                                  type: string
                                                optional:
                                                  type: boolean
                                              required:
                                                - key
                                      required:
                                        - name
                                  image:
                                    type: string
                                  name:
                                    type: string
                                required:
                                  - name
                          required:
                            - containers
                  required:
                    - template
              required:
                - reagent
                - deployment
  # either Namespaced or Cluster
  scope: Namespaced
  names:
    # plural name to be used in the URL: /apis/<group>/<version>/<plural>
    plural: reactors
    # singular name to be used as an alias on the CLI and for display
    singular: reactor
    # kind is normally the CamelCased singular type. Your resource manifests use this.
    kind: Reactor
    # shortNames allow shorter string to match your resource on the CLI
    shortNames:
      - rt
